# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aec5852904db8b12c4aec29d9631da876c0c4767f9ef9fb18fe612c1204a0e48527dbf70355b8e60eb1a0e9da408aabbbc36f430956a52a5de749aae3b7540b

test:
  secret_key_base: 25dc41fd36f7975cf3359ff288f2329a7e1dd4f091ffb21b94cc23d780d1d3494e439e2fdef0175d2f903a1a486f705a90da615cf4fc5d99d48e8cda46e1587a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
